### ISSUE TITLE
FXIconCreator damaged on macOS

### ISSUE THREAD

**Issue by mipastgt** [lanthale/FXIconCreator#1]
If you install the FXIconCreator.app from the DMG file downloaded from GitHub, then the extracted app-file cannot be executed. You get the message that the file is damaged. (See screenshot)
<img width="452" alt="Bildschirmfoto 2021-12-06 um 10 20 10" src="https://user-images.githubusercontent.com/16735714/144822929-64172dc3-1bf2-455c-a479-f1adac5728fb.png">
This happens because the app is not properly signed and notarized by Apple. In order to fix this every user has to run the following command: `sudo xattr -r -d com.apple.quarantine ~/Applications/FXIconCreator.app` (depending on where you have installed the app). After that it can be used normally. This only has to be done once. You should add this information somewhere on the GitHub page so that people know what to do. (Your account must have the sudoer rights to be able to do this!)

**Comment by lanthale** [comment]
I have now added the information to the readme with your way and with a way without using the terminal app
